const path = require('path');
const os = require('os');
const fs = require('fs');
const ExcelJS = require('exceljs');
const { getPage } = require('./browser');
const logger = require('../utils/logger');
const { delay } = require('../utils/delay');

// ─── Wait Helpers ─────────────────────────────────────────────────────────────

/**
 * Poll for a DOM element until it appears or the timeout is reached.
 */
async function waitForElement(selector, timeout = 10000, interval = 1000) {
  let elapsed = 0;
  while (elapsed < timeout) {
    const found = await getPage().evaluate((sel) => !!document.querySelector(sel), selector);
    if (found) return true;
    await delay(interval);
    elapsed += interval;
  }
  throw new Error(`Element "${selector}" not found after ${timeout / 1000}s`);
}

async function waitForNavigation() {
  await getPage().waitForNavigation({ waitUntil: 'networkidle2' });
}

// ─── Click Actions ────────────────────────────────────────────────────────────

async function click(selector) {
  await waitForElement(selector);
  logger.debug(`Clicking: ${selector}`);
  await getPage().click(selector);
}

/**
 * Click an element via page.evaluate — useful when Puppeteer's native click
 * is blocked by overlapping elements.
 */
async function clickWithEvaluate(selector) {
  logger.debug(`Clicking via evaluate: ${selector}`);
  await getPage().evaluate((sel) => document.querySelector(sel).click(), selector);
}

// ─── Input Actions ────────────────────────────────────────────────────────────

/**
 * Clear an input field and type new text into it.
 */
async function typeInto(selector, text) {
  await waitForElement(selector);
  await getPage().focus(selector);
  await getPage().evaluate((sel) => { document.querySelector(sel).value = ''; }, selector);
  await getPage().type(selector, text);
  logger.debug(`Typed into ${selector}`);
}

/**
 * Attach a local file to a file input element.
 */
async function uploadFile(filePath, selectorInput = "input[type='file']") {
  await waitForElement(selectorInput);
  const input = await getPage().$(selectorInput);
  if (!input) throw new Error(`Upload input not found: ${selectorInput}`);
  await input.uploadFile(filePath);
  logger.debug(`Uploaded file "${filePath}" to ${selectorInput}`);
}

// ─── Read Actions ─────────────────────────────────────────────────────────────

async function elementExists(selector) {
  return getPage().evaluate((sel) => !!document.querySelector(sel), selector);
}

async function getTextContent(selector) {
  return getPage().evaluate((sel) => document.querySelector(sel).innerText, selector);
}

// ─── Upload Process ───────────────────────────────────────────────────────────

/**
 * Poll the upload queue row until the status no longer contains `content`
 * (i.e. the "process" state has cleared), then return the final row text.
 */
async function waitForUploadProcess(selector, content, interval = 500, timeout = 10000) {
  let elapsed = 0;
  while (elapsed < timeout) {
    const text = await getTextContent(selector);
    if (text.toLowerCase().includes('\t') && !text.toLowerCase().includes(content)) {
      return text;
    }
    await delay(interval);
    elapsed += interval;
  }
  throw new Error(`Upload process content "${content}" not found after ${timeout / 1000}s`);
}

// ─── Error File Helpers ───────────────────────────────────────────────────────

/**
 * Download the error Excel file generated by ESB after a failed upload.
 * First tries the Download button inside the upload queue table
 * (.dataTables_scroll td.text-center a.upload-queue-download-btn[title="Download"]).
 * Falls back to navigating directly to `fallbackUrl` if the button is not found.
 * Returns the local path of the downloaded file, or null if nothing was downloaded.
 */
async function downloadErrorFile(fallbackUrl = null) {
  const page = getPage();
  const downloadPath = fs.mkdtempSync(path.join(os.tmpdir(), 'esb-err-'));

  // Configure CDP to save downloads to the temp directory
  const client = await page.createCDPSession();
  await client.send('Browser.setDownloadBehavior', {
    behavior: 'allow',
    downloadPath,
    eventsEnabled: true,
  });

  let downloaded = false;

  const btnSelector = '.dataTables_scroll td.text-center a.upload-queue-download-btn[title="Download"]';
  const btnExists = await page.evaluate((sel) => !!document.querySelector(sel), btnSelector);

  if (btnExists) {
    logger.info('Downloading error file via table Download button...');
    await page.evaluate((sel) => document.querySelector(sel).click(), btnSelector);
    downloaded = true;
  } else if (fallbackUrl) {
    logger.info(`Downloading error file via URL: ${fallbackUrl}`);
    await page.evaluate((url) => { window.location.href = url; }, fallbackUrl);
    downloaded = true;
  }

  if (!downloaded) {
    logger.warn('Download button not found and no fallback URL provided.');
    return null;
  }

  const filePath = await waitForDownloadedFile(downloadPath, 15000);
  logger.info(`Error file downloaded: ${filePath}`);
  return filePath;
}

/**
 * Poll a directory until a fully downloaded file appears (ignores .crdownload partials).
 */
async function waitForDownloadedFile(dir, timeout = 15000) {
  const start = Date.now();
  while (Date.now() - start < timeout) {
    const files = fs.readdirSync(dir).filter((f) => !f.endsWith('.crdownload'));
    if (files.length > 0) return path.join(dir, files[0]);
    await delay(500);
  }
  throw new Error(`Error file was not downloaded within ${timeout / 1000}s`);
}

/**
 * Parse the ESB error Excel file and extract per-row error messages.
 *
 * Expected file layout (header on row 4):
 *   # | Voucher Code | Branch Name | Voucher Amount | Start Date | End Date | Additional Information | <error message>
 *
 * The actual error text lives in the column immediately after "Additional Information"
 * and may contain multiple errors separated by commas.
 *
 * Returns an array of:
 *   { row, voucherCode, branchName, additionalInfo, errorMessages: string[] }
 */
async function parseErrorExcel(filePath) {
  const workbook = new ExcelJS.Workbook();
  await workbook.xlsx.readFile(filePath);
  const sheet = workbook.worksheets[0];

  // Locate the header row by finding the row that contains "Voucher Code"
  let headerRowIdx = -1;
  let headers = [];
  sheet.eachRow((row, rowNumber) => {
    if (headerRowIdx !== -1) return;
    const values = row.values.slice(1).map((v) => String(v ?? '').trim().toLowerCase());
    if (values.some((v) => v.includes('voucher code'))) {
      headerRowIdx = rowNumber;
      headers = values;
    }
  });

  if (headerRowIdx === -1) {
    logger.warn('Unrecognised error file format — "Voucher Code" header not found.');
    return [];
  }

  const colVoucherCode = headers.findIndex((h) => h.includes('voucher code'));
  const colBranch      = headers.findIndex((h) => h.includes('branch'));
  const colAdditional  = headers.findIndex((h) => h.includes('additional'));
  // Error message column is immediately after "Additional Information"
  const colErrorMsg    = colAdditional + 1;

  const errors = [];
  sheet.eachRow((row, rowNumber) => {
    if (rowNumber <= headerRowIdx) return;
    const vals = row.values.slice(1);

    const errorMessage = String(vals[colErrorMsg] ?? '').trim();
    if (!errorMessage) return; // skip rows without an error message

    errors.push({
      row: rowNumber,
      voucherCode:    String(vals[colVoucherCode] ?? '').trim(),
      branchName:     String(vals[colBranch]      ?? '').trim(),
      additionalInfo: String(vals[colAdditional]  ?? '').trim(),
      // Split comma-separated errors into individual messages
      errorMessages: errorMessage.split(/,\s*/).map((e) => e.trim()).filter(Boolean),
    });
  });

  return errors;
}

// ─── Voucher Check ────────────────────────────────────────────────────────────

/**
 * Search for a voucher by code using the filter input in the table header
 * (thead tr#grid-voucher-filters input[name="MsVoucher[voucherID]"]).
 * Clears the input, types the code, presses Enter to trigger the search,
 * then reads the matching row from tbody.
 * Returns null if no matching row is found.
 */
async function checkVoucherByCode(voucherCode) {
  const page = getPage();
  const filterInput = '#grid-voucher-container thead tr#grid-voucher-filters input[name="MsVoucher[voucherID]"]';

  await waitForElement(filterInput);
  await page.evaluate((sel) => { document.querySelector(sel).value = ''; }, filterInput);
  await page.type(filterInput, voucherCode);
  await page.keyboard.press('Enter');

  // Wait for the table to reload with filtered results
  await delay(1500);

  return page.evaluate((code) => {
    const row = document.querySelector(
      `#grid-voucher-container table.kv-grid-table tbody tr[data-key="${code}"]`
    );
    if (!row) return null;

    const td = (seq) => row.querySelector(`td[data-col-seq="${seq}"]`)?.innerText?.trim() || '-';

    return {
      voucherCode:       code,
      branch:            td('3'),
      startDate:         td('4'),
      endDate:           td('5'),
      minSalesAmount:    td('7'),
      voucherAmount:     td('8'),
      voucherSalesPrice: td('9'),
      additionalInfo:    td('10'),
      status:            td('11'),
    };
  }, voucherCode);
}

module.exports = {
  waitForElement,
  waitForNavigation,
  click,
  clickWithEvaluate,
  typeInto,
  uploadFile,
  elementExists,
  getTextContent,
  waitForUploadProcess,
  downloadErrorFile,
  parseErrorExcel,
  checkVoucherByCode,
};
